import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Login() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>      
        <body>
            <h1>VMI Turnout System Login</h1>
            <label for ="lblEmail">E-Mail: </label>
            <input type ="text" id="txtEmail" name="txtEmail" placeholder=" "></input>
            <label for ="lblPassword">Password: </label>
            <input type ="text" id="txtPassword" name="txtPassword" placeholder=" "></input>
            <button type="button">Login</button>
            <br></br>
            <a href=" ">Sign Up Here</a>
            <br></br>
            <a href=" ">Forgot Password?</a>
  
  
        </body>
        <footer className={styles.footer}>
        </footer>
      </div>
    )
  }
  
  function getLoginInfo(){
    var loginEn
  }